### ISSUE TITLE
'Error=INVALID_PARAMETERS'. It is missing 'token' field.

### ISSUE THREAD

**Issue by long1eu** [firebase/firebase-ios-sdk#7241]
Potentially related to https://github.com/firebase/firebase-ios-sdk/issues/5970

### Environment
  * Xcode version: 12.3
  * Firebase SDK version: 6.33.0
  * Installation method: CocoaPods
  * Firebase Component: Messaging
  
### [REQUIRED] Problem
We get `Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field.` when we try to register to a topic.

#### Relevant Logs:

```
2021-01-02 05:26:54.937529+0200 Runner_dev[56092:5378014] Metal API Validation Enabled
2021-01-02 05:26:54.996240+0200 Runner_dev[56092:5378215] 6.33.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
2021-01-02 05:26:54.996556+0200 Runner_dev[56092:5378215] 6.33.0 - [Firebase/Core][I-COR000001] Configuring the default app.
2021-01-02 05:26:54.996629+0200 Runner_dev[56092:5378215] 6.33.0 - [Firebase/Installations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2021-01-02 05:26:54.998412+0200 Runner_dev[56092:5378218] 6.33.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001011] App Delegate Proxy is disabled.
2021-01-02 05:26:54.998571+0200 Runner_dev[56092:5378014] [Firebase/Crashlytics] Version 4.6.2
2021-01-02 05:26:54.999013+0200 Runner_dev[56092:5378218] 6.33.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics] Running on iPhone13,2, 14.3.0 (18C66)
2021-01-02 05:26:54.999720+0200 Runner_dev[56092:5378218] 6.33.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Settings] No settings were cached
2021-01-02 05:26:55.008106+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Crash:Reports:Event] Registered Firebase Analytics event listener
2021-01-02 05:26:55.008218+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Crashlytics][I-CLS000000] Automatic data collection is enabled.
2021-01-02 05:26:55.008331+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Crashlytics][I-CLS000000] Unsent reports will be uploaded at startup
2021-01-02 05:26:55.009972+0200 Runner_dev[56092:5378241] 6.33.0 - [Firebase/Messaging][I-FCM002000] FIRMessaging library version 4.7.1
2021-01-02 05:26:55.010232+0200 Runner_dev[56092:5378241] 6.33.0 - [GULReachability][I-REA902003] Monitoring the network status
2021-01-02 05:26:55.062208+0200 Runner_dev[56092:5378221] 6.33.0 - [GULReachability][I-REA902003] Monitoring the network status
2021-01-02 05:26:55.062241+0200 Runner_dev[56092:5378221] 6.33.0 - [GULReachability][I-REA902003] Monitoring the network status
2021-01-02 05:26:55.062263+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS024000] Debug mode is on
2021-01-02 05:26:55.062285+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS005000] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
2021-01-02 05:26:55.062307+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60803000 started
2021-01-02 05:26:55.062395+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-01-02 05:26:55.062670+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS023009] Debug logging enabled
2021-01-02 05:26:55.062797+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS023207] To enable verbose logging set the following application argument: -FIRAnalyticsVerboseLoggingEnabled (see http://goo.gl/RfcP7r)
2021-01-02 05:26:55.063005+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS025036] App Delegate Proxy is disabled
2021-01-02 05:26:55.166043+0200 Runner_dev[56092:5378234] flutter: Observatory listening on http://127.0.0.1:51883/9RmHJHjCSwk=/
2021-01-02 05:26:55.255386+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS002002] APMExperimentAlarm scheduled to fire in approx. (s): 12164.78763198853
2021-01-02 05:26:55.348074+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-01-02 05:26:55.348428+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS029014] Successfully parsed a configuration. Version: 1607857999798113
2021-01-02 05:26:55.348909+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS023016] Analytics is ready to receive events
2021-01-02 05:26:55.446264+0200 Runner_dev[56092:5378237] 6.33.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
2021-01-02 05:26:55.448304+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
2021-01-02 05:26:55.449173+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS002002] Engagement timer scheduled to fire in approx. (s): 3600
2021-01-02 05:26:55.449205+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2021-01-02 05:26:55.449252+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
2021-01-02 05:26:55.572487+0200 Runner_dev[56092:5378238] 6.33.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
2021-01-02 05:26:55.572563+0200 Runner_dev[56092:5378238] 6.33.0 - [GULReachability][I-REA902004] Network status has changed. Code:1, status:Disconnected
2021-01-02 05:26:55.572626+0200 Runner_dev[56092:5378238] 6.33.0 - [GULReachability][I-REA902004] Network status has changed. Code:2, status:Connected
2021-01-02 05:26:55.579406+0200 Runner_dev[56092:5378240] 6.33.0 - [Firebase/Auth][I-AUT000011] Provisioning profile has specifically provisioned devices, most likely a Dev profile.
2021-01-02 05:26:55.579553+0200 Runner_dev[56092:5378240] 6.33.0 - [Firebase/Auth][I-AUT000012] APNS Environment in profile: development
2021-01-02 05:26:55.579601+0200 Runner_dev[56092:5378240] 6.33.0 - [Firebase/Installations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
2021-01-02 05:26:55.579673+0200 Runner_dev[56092:5378237] 6.33.0 - [Firebase/Analytics][I-ACS031010] Tracking view controller. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:55.597823+0200 Runner_dev[56092:5378237] 6.33.0 - [Firebase/Analytics][I-ACS023051] Logging event: origin, name, params: auto, screen_view (_vs), {
    ga_event_origin (_o) = auto;
    ga_screen_class (_sc) = FlutterViewController;
    ga_screen_id (_si) = -2495601682029743000;
}
2021-01-02 05:26:55.598447+0200 Runner_dev[56092:5378240] 6.33.0 - [Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = FlutterViewController;
    ga_screen_id (_si) = -2495601682029743000;
}
2021-01-02 05:26:55.601381+0200 Runner_dev[56092:5378240] 6.33.0 - [Firebase/Analytics][I-ACS023072] Event logged. Event name, event params: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = FlutterViewController;
    ga_screen_id (_si) = -2495601682029743000;
}
2021-01-02 05:26:55.602636+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): 0.9762150049209595
2021-01-02 05:26:55.846242+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Firestore][I-FST000001] Initializing. Current user: 0JaBFEdrWVSTRd8dRwH4DADdeQw2
2021-01-02 05:26:55.846284+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Firestore][I-FST000001] Using full collection scan to execute query: Query(canonical_id=env/dev/users/0JaBFEdrWVSTRd8dRwH4DADdeQw2|f:|ob:__name__asc)
2021-01-02 05:26:55.846310+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) start
2021-01-02 05:26:55.846359+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Auth][I-AUT000002] Token auto-refresh enabled.
2021-01-02 05:26:55.846380+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Auth][I-AUT000004] Token auto-refresh scheduled in 17:43 for the new token.
2021-01-02 05:26:55.846397+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Firestore][I-FST000001] Creating Firestore stub.
2021-01-02 05:26:55.859037+0200 Runner_dev[56092:5378223] flutter: locale.languageCode: en
2021-01-02 05:26:56.104979+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.105086+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.105548+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.105953+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.106143+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.106827+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.106876+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.106895+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.125365+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.125405+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.125466+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.146705+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) headers (whitelisted): date: Sat, 02 Jan 2021 03:26:56 GMT
2021-01-02 05:26:56.146751+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) response: <ListenResponse 0x16ec0e650>: {
  target_change {
    target_change_type: ADD
    target_ids: 2
  }
}
2021-01-02 05:26:56.191668+0200 Runner_dev[56092:5378223] flutter: subscribeToTopic: 0JaBFEdrWVSTRd8dRwH4DADdeQw2
2021-01-02 05:26:56.196360+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) headers (whitelisted): date: Sat, 02 Jan 2021 03:26:56 GMT
2021-01-02 05:26:56.199775+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) headers (whitelisted): date: Sat, 02 Jan 2021 03:26:56 GMT
2021-01-02 05:26:56.199810+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) response: <ListenResponse 0x16ec0e650>: {
  target_change {
    target_change_type: CURRENT
    target_ids: 2
    resume_token: "\n\t\010\314\247\264\356\246\374\355\002"
    read_time {
      seconds: 1609558016
      nanos: 201676000
    }
  }
}
2021-01-02 05:26:56.199852+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) headers (whitelisted): date: Sat, 02 Jan 2021 03:26:56 GMT
2021-01-02 05:26:56.199885+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) response: <ListenResponse 0x16ec0e650>: {
  target_change {
    resume_token: "\n\t\010\314\247\264\356\246\374\355\002"
    read_time {
      seconds: 1609558016
      nanos: 201676000
    }
  }
}
2021-01-02 05:26:56.200089+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Installations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
2021-01-02 05:26:56.200176+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Installations][I-FIS002001] -[FIRInstallationsIDController installationWithValidAuthTokenForcingRefresh:0], appName: __FIRAPP_DEFAULT
2021-01-02 05:26:56.200211+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Messaging][I-FCM017000] Topic subscription request: sender=cyl-5UqSbkEYv2maOWAChY:APA91bG17lCa7nIXl04sWQX7nxG3lTMI-mqaphhZlQlSPZJObMW0_0bnTimaHHzDrWSRnHRvbsB3gUWOexvZ5t9LKt61Ul06HocWRQ86MIwUugWRe17UnkfZroR3hwfr6SEh7-LZE9GV&app=io.supy.app&device=5179847106474540389&app_ver=0.1.56&X-gcm.topic=/topics/0JaBFEdrWVSTRd8dRwH4DADdeQw2&X-scope=/topics/0JaBFEdrWVSTRd8dRwH4DADdeQw2
2021-01-02 05:26:56.419717+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Messaging][I-FCM017002] Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field.
2021-01-02 05:26:56.419883+0200 Runner_dev[56092:5378014] FLTFirebaseMessaging: An error occurred while calling method Messaging#subscribeToTopic, errorOrNil => {
    NSLocalizedFailureReason = "Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field.";
}
2021-01-02 05:26:56.420186+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field." UserInfo={NSLocalizedFailureReason=Invalid registration response :'Error=INVALID_PARAMETERS'. It is missing 'token' field.}
2021-01-02 05:26:56.424420+0200 Runner_dev[56092:5378223] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String' in type cast
#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:89:26)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:88:11)
#3      platformExceptionToFirebaseException (package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart:26:9)
#4      convertPlatformException (package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart:15:10)
#5      MethodChannelFirebaseMessaging.subscribeToTopic (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:365:13)
<asynchronous suspension>
2021-01-02 05:26:56.667173+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS002001] Measurement timer fired
2021-01-02 05:26:56.667390+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS002003] Measurement timer canceled
2021-01-02 05:26:56.669156+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = FlutterViewController;
    ga_screen_id (_si) = -2495601682029743000;
}
2021-01-02 05:26:56.678533+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS012018] Saving bundle. size (bytes): 465
2021-01-02 05:26:56.679123+0200 Runner_dev[56092:5378239] 6.33.0 - [Firebase/Analytics][I-ACS023116] Bundle added to the upload queue. BundleID, timestamp (ms): 10, 1609558015578
2021-01-02 05:26:56.698484+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS023039] Measurement data sent to network. Timestamp (ms), data: 1609558016697, <APMPBMeasurementBatch: 0x2838b8ff0>
2021-01-02 05:26:56.703803+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS900000] Uploading data. Host: https://app-measurement.com/a
2021-01-02 05:26:56.720103+0200 Runner_dev[56092:5378221] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.746618+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.746692+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.746728+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.746812+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.746879+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.746964+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.747042+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.747121+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS031006] View controller already tracked. Class, ID: FlutterViewController, -2495601682029743000
2021-01-02 05:26:56.849484+0200 Runner_dev[56092:5378238] 6.33.0 - [Firebase/Analytics][I-ACS901006] Received SSL challenge for host. Host: https://app-measurement.com/a
2021-01-02 05:26:56.909283+0200 Runner_dev[56092:5378240] 6.33.0 - [Firebase/Analytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
2021-01-02 05:26:56.912984+0200 Runner_dev[56092:5378219] 6.33.0 - [Firebase/Analytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -0.3347909450531006
2021-01-02 05:26:56.916533+0200 Runner_dev[56092:5378219] 6.33.0 - [Firebase/Analytics][I-ACS002003] Measurement timer canceled
2021-01-02 05:27:36.357237+0200 Runner_dev[56092:5378226] [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
2021-01-02 05:27:41.235098+0200 Runner_dev[56092:5378536] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) headers (whitelisted): date: Sat, 02 Jan 2021 03:26:56 GMT
2021-01-02 05:27:41.235193+0200 Runner_dev[56092:5378536] 6.33.0 - [Firebase/Firestore][I-FST000001] WatchStream (2806acc18) response: <ListenResponse 0x16ec9a650>: {
  target_change {
    resume_token: "\n\t\010\376\302\357\203\247\374\355\002"
    read_time {
      seconds: 1609558061
      nanos: 212030000
    }
  }
}
```

**Comment by chliangGoogle** [comment]
Your client seems not getting a FCM registration token properly. Can you try with a fresh install and if still not working, attach me the debugLog with first run after installation?

**Comment by diegomgarcia** [comment]
Hi guys, I'm having this exact issue here to. 

I'm using an flutter application and it was working nice until I've ported this app to another apple account, after that it loses the apn, certs and everything else on apple, I thing the migration tools doesn't work as it should.  So I've do all the process again and changed the apn in firebase console, change the certificates and everything else, upgrade my firebase messaging migrate the old commands to the new ones for the new api and run, so when I try to subscribe to topic it gives me that error.

Any tips on what can be happening ?

**Comment by chliangGoogle** [comment]
@diegomgarcia Your case seems quite different since you made significant changes to Apple credentials. Can you file a new issue so the discussion here is not redirected on the credential part.
